### ISSUE TITLE
Detect asset pipeline availability

### ISSUE THREAD

**Issue by jch** [jch/html-pipeline#1]
In the github app, the emoji icons are frozen to public/images, and urls to images are coded relative to the value of `:asset_root`. It'd be preferable to detect the availability of the asset-pipeline and use `asset_path` when it's available.

**Comment by BM5k** [comment]
:+1: for asset pipeline support, because as it is now my heroku app is serving static assets (for the [emoji][1] filter), instead of having them automagically cached by cloudfront.

PS the asset pipeline instructions in the gemoji [readme][2] are out of date.

[1]: https://github.com/github/gemoji/
[2]: https://github.com/github/gemoji/blob/ac3620cf89baca5f50ddf9cd0d759aea009086d1/README.md
