### ISSUE TITLE
Why isn't <span> whitelisted by default?

### ISSUE THREAD

**Issue by rymohr** [jch/html-pipeline#183]
Curious if this was intentional or an oversight:
https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L45

**Comment by patrickberkeley** [comment]
I'm wondering the same thing. I think it might be a mistake that `span` is listed under [`attributes`](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L72). I haven't been able to find anything saying that `span` is a valid HTML attribute.

**Comment by jnvm** [comment]
@patrickberkeley see:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col#attr-span
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup#attr-span

@rymohr I'd like to know too.

At present the whitelist offers 0 naturally unstyled inline elements intended for arbitrary text.  It looks like only `<ruby>`, `<rt>`, and `<rp>` may be misused for this purpose. (`<a>` can be used, be breaks child links its contents might contain)

My use case is a markdown generator (intended for primary viewing on github) which retains user-supplied textual descriptions (of arbitrary content) on rebuilds.  I so happen to want to offer the ability to have the textual description of something literally _to the right_ of the term it's describing, so `<dt>` and `<dd>` are out of the question since they're block elements that force a newline.  The only way I can do this and survive github's filtering is to misuse the ruby elements, which makes me 😞.

It'd be nice if `<span>` was allowed.
