### ISSUE TITLE
Support limited use of the HTML 'style' attribute

### ISSUE THREAD

**Issue by mhelvens** [jch/html-pipeline#192]
I've seen a number of specific feature requests about styling, such as [this one](https://github.com/github/markup/issues/369) about color. But surprisingly, I could find none regarding the actual HTML `style` attribute.

That attribute is currently disallowed by the [sanitization filter](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb). I agree that full use of the `style` attribute would be too powerful - positioning and sizing properties might mess up the whole layout.

I propose that a 'css whitelist' is created, allowing limited use of the `style` attribute. I'm sure many developers would like to be able to use `color`, `border`, `padding`, and so on, to improve the style of their documentation.

(PS: This issue was originally posted on [github/markup](https://github.com/github/markup/issues/486), but it seems to belongs here instead.)

**Comment by harlanhaskins** [comment]
:+1:

**Comment by shabnams** [comment]
Yes please. Color would be great.

**Comment by zackphilipps** [comment]
:+1:

**Comment by jch** [comment]
Closing because we have no plans to support this.

**Comment by peterflynn** [comment]
@jch Curious for the rationale? Does GitHub have any other path in mind for getting colored text in wiki content?

**Comment by jch** [comment]
@peterflynn your wiki suggestion is a good one, but it's an application concern, not a library one. While GitHub does use html-pipeline internally, this isn't a good place to capture feature suggestions. This can be achieved today by customizing the upstream sanitization filter to be different for a specific pipeline one would like to whitelist.

I recommend writing in at https://github.com/contact if you have ideas about how our wiki's should change. Hope that helps!

**Comment by mhelvens** [comment]
I'm a bit confused. This repo is definitely the place where specific HTML tags are whitelisted, and it seems like an obvious place to whitelist further markup. I initially put this feature request in github/markup, but they closed the issue because they do "not perform the HTML sanitization".

The suggestion to contact GitHub privately seems absurd. Isn't GitHub all about openly discussing this kind of thing? And that very contact form directs us to open an issue for markup related stuff.

**Comment by h-h-h-h** [comment]
:+1:

**Comment by ericnewton76** [comment]
Best option is to santize the style attribute in html, however there's another route, where you simply invent another markdown tag for color: {fg:blue}blue foreground{/fg:blue} {bg:red}red background{/bg:red} {fg:#ccc}Silver showing support for color numbers{/fg:#ccc}

**Comment by svnpenn** [comment]
@mhelvens you are right. When GitHub tells us to create issue at html-pipeline
repo, then @jch tells us to contact GitHub, one party is wrong.

**Comment by svnpenn** [comment]
@mhelvens you are right. When GitHub tells us to create issue at html-pipeline
repo, then @jch tells us to contact GitHub, one party is wrong.

@jch is especially suspicious because **he is a GitHub employee**. Why is an
employee essentially blowing us off with http://github.com/contact when he owns
the very repo that this issue concerns?

**Comment by svnpenn** [comment]
@mhelvens you are right. When GitHub tells us to create issue at html-pipeline
repo, then @jch tells us to contact GitHub, one party is wrong.

@jch is especially suspicious because **he is a GitHub employee**. Why is an
employee essentially blowing us off with http://github.com/contact when he owns
the very repo that this issue concerns?

Plus his rationale makes no sense:

> This can be achieved today by customizing the upstream sanitization filter

**This repo is the upstream filter**, so what he is saying is absurd. Please
GitHub, get your house in order.

**Comment by jeffpeiyt** [comment]
the white background in grey table rows could be improved. would be great that user can overwrite their css at least to enable transparent PNG...
http://stackoverflow.com/questions/33154030/remove-background-color-on-image-inside-markdown-table

**Comment by devbharat** [comment]
So, where do we stand here?

**Comment by svnpenn** [comment]
@devbharat its typical bureaucracy: they would rather introduce new features:

http://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

than fix old problems:

http://github.com/isaacs/github

Fixing old problems is actually what the community wants, but wont happen because it is not sexy to the sponsors, who actually pay the bills:

http://github.com/blog/2259-mission-report-github-universe

**Comment by 0xced** [comment]
A few days ago, I wrote [an issue](https://github.com/AFNetworking/AFNetworking/issues/3710) with a very long log dump. I had prepared it with different colors highlighting important points to be easier to comprehend but only the bold formatting remained. ☹️

Could you please reconsider having some basic support for colors?

**Comment by abrist** [comment]
Color support would be fantastic.  Especially for all of us that write shell code with ansi.

**Comment by svnpenn** [comment]
https://github.com/github/markup/issues/945

**Comment by mhelvens** [comment]
Just FYI: This feature request was not just about color.

**Comment by nicholaswmin** [comment]
Please don't ever do this. This is exactly what markdown was build to avoid.
